threaded replies
hubotio/hubot pull request #1557
Opened 2021-07-20 02:23 UTC by esirko

Building off of some earlier hackathon work to enable threaded replies in Slack messages for RPC chatops, I would like to extend it to all chatops. This is part of the changes that would be necessary to allow you to specify `--thread` or `--nothread` to any hubot chatop to make it threaded or not threaded.  

- https://github.com/github/hubot-slack/pull/21 for the prior work, for reference
- https://github.com/github/hubot-slack/pull/22 for a sibling PR to this one

2023-04-23 02:58 UTC, joeyguerra commented
I think threaded replies are better left to the chat adapter to implement instead of adding it as a core concept in Hubot.

2023-04-25 21:36 UTC, adligit2 approved these changes

2023-04-25 21:37 UTC, adligit2 reviewed
review

2023-04-25 21:44 UTC, adligit2 requested changes
submit

2023-04-25 21:44 UTC, adligit2 commented on src/listener.js
submit

2023-04-25 21:45 UTC, adligit2 commented
```javascript

```

2023-04-28 18:13 UTC, technicalpickles commented
@adligit2 it looks like you may be testing something. Please find another place to do so.

2023-04-28 19:00 UTC, joeyguerra commented
My concerns with this PRs threaded reply design boils down to the fact that Slack's threaded replies concept leaks into Hubot's code. Refer to the companion code in [`github/hubot-slack`](https://github.com/github/hubot-slack/pull/22/files). It requires a property, `requestedThreadStyle` be set (responsibility) within Hubot's *core*.

An alternative design would be passing through an "adapter context" (a whole object instead of just a property) that can just be passed through to the adapter from within Hubot's *core*. That way, the only *concept* that Hubot is aware of is the concept of an "adapter context" which doesn't require Hubot to *know* about the details of that object. Hubot will just ensure that the object is passed through to the adapter. The Adapter can then use it to model a threaded reply.

2023-07-24 01:08 UTC, closed without merging